### ISSUE TITLE
The config is reset

### ISSUE THREAD

**Issue by 7jon** [AlaDyn172/UReport#2]
Hello, I have the problem that my config always resets when I edit it. I want to translate the messages into German but when I only remove the "t" in "report", save it and reload the server the config is default again. I hope you can help me.

**Comment by AlaDyn172** [comment]
You need to edit the config when the server is turned off, and after you succesfully edited your config just start the server ;).
Let me know if it worked!

**Comment by 7jon** [comment]
Thank you ! I'm really surprised that you have responded so quickly!
And now it works, I only was used from other plugins that one can change the config during the operation and "activate" it with a reload.
Thanks a lot again and have much fun programming java ;-).

**Comment by AlaDyn172** [comment]
Great!
